esphome:
  name: moisture-sensor-name
  friendly_name: Moisture Name

esp32: 
  board: lolin_s2_mini 
  variant: esp32s2 
  framework: 
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
  
# WIFI Credentials
wifi:
  ssid: "esp_session"
  password: "esp12345"
  ap:

sensor:
  - platform: adc
    pin: 3
    name: "Soil Moisture"
    update_interval: 10s
#    unit_of_measurement: "%"
    attenuation: 11db
#    filters:
#    - median:
#        window_size: 7
#        send_every: 4
#        send_first_at: 1
#    - calibrate_linear:
#        - 0.912 -> 100.00
#        - 2.52 -> 0.00
#    - lambda: |
#        if (x < 0) return 0; 
#        else if (x > 100) return 100;
#        else return (x);
#    accuracy_decimals: 0
    

captive_portal:
web_server:
